###
# SPDX-License-Identifier: AGPL-3.0
#
# Author: Bernd rederlechner <bernd.rederlechner@t-systems.com>
#
# Assemble a customisation for trunk (no backports) and stable
# (backport xor trunk)
#
# It creates review (user-specific) customisations branches
# - customisation-<user>-<trunk>
# - customisation-<user>-<stable>

name: MCLOUD custom app versions

on:
  workflow_dispatch:

jobs:
  build-custom:
    strategy:
      fail-fast: false
      matrix:
        custombase: [ "main", "nmcstable/25.0.6" ]
    uses: nextmcloud/.github/.github/workflows/nmc-custom-assembly.yml@master
    with:
      trunk: "master"
      stable: ${{ matrix.custombase }}
      result: ${{ format('customisation-{0}-{1}', github.actor, matrix.custombase) }}
    secrets: inherit
