name: Trigger GitLab Image Pipeline

on:
  schedule:
    - cron: "0 15 * * *"
  
  workflow_call:
  
  workflow_dispatch: # manual

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Workflow run ID
      id: get-workflow-run-id
      run: |
        # Fetch workflows
        WORKFLOW_NAME="Store version artifacts"
        WORKFLOW_RUN_ID=$(curl -s "https://api.github.com/repos/nextmcloud/.github/actions/runs" | jq -r --arg WORKFLOW_NAME "$WORKFLOW_NAME" '.workflow_runs[] | select(.name == $WORKFLOW_NAME) | .id')
        echo "Workflow Run ID: $WORKFLOW_RUN_ID"
        echo "::set-output name=workflow_run_id::$WORKFLOW_RUN_ID"

      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_RUN_ID: $WORKFLOW_RUN_ID

    - name: Cleanup previous artifacts
      run: rm -f versions_combined

    - name: Get Artifact ID
      id: get-artifact-id
      run: |
        # Get the latest artifact ID
        ARTIFACT_ID=$(curl -s "https://api.github.com/repos/nextmcloud/.github/actions/runs/$WORKFLOW_RUN_ID/artifacts" | jq -r '.artifacts[0].id')
        echo "Artifact ID: $ARTIFACT_ID"
        echo "::set-output name=artifact_id::$ARTIFACT_ID"
      
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_RUN_ID: ${{ steps.get-workflow-run-id.outputs.workflow_run_id }}
          ARTIFACT_ID: $ARTIFACT_ID

    - name: Download versions artifact
      id: download-artifact
      run: |
        # Download the artifact from the store-version-artifacts workflow
        FILENAME=$(curl -LJO -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/nextmcloud/actions/runs/$WORKFLOW_RUN_ID/artifacts/$ARTIFACT_ID/versions-combined.txt" \
          -w '%{filename_effective}')
        echo "Downloaded file: $FILENAME"
      
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_RUN_ID: ${{ steps.get-workflow-run-id.outputs.workflow_run_id }}
          ARTIFACT_ID: ${{ steps.get-artifact-id.outputs.artifact_id }}
          FILENAME: $FILENAME
        # Extract the archive

    - name: Print contents of versions-combined.txt
      run: cat ${{ github.workspace }}/version-store/versions-combined.txt
      

    - name: Trigger Nmc deployment image building with versions
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_IMAGE_TRIGGER_TOKEN }}
      run: |
        # Read the versions from the file
        VERSIONS=$(cat versions-combined.txt)
        
        # Trigger the GitLab pipeline with versions
        curl -X POST \
          --fail \
          -F token=$GITLAB_TOKEN \
          -F ref=master \
          -F variables[VERSIONS]="$VERSIONS" \
          https://gitlab.devops.telekom.de/api/v4/projects/37742/trigger/pipeline
