###
# SPDX-License-Identifier: AGPL-3.0
#
# Author: Bernd rederlechner <bernd.rederlechner@t-systems.com
#
# Find all open customisation PRs with corresponding branches 
# and create a stable backport branch and stable backport PR
# if automatic rebasing of the master works. 
# 
# 
#

name: MCLOUD stable baseline

on:
  workflow_call:
    inputs:
      trunk:
        description: trunk branch name for the repo (e.g., master, main, trunk, ...)
        required: true
        type: string
      stable:
        description: stable branch to create baseline PRs for 
        required: false
        type: string
      

jobs:
  create-stables:
    runs-on: ubuntu-latest
    env:
      CUSTOM_REPO:   ${{ github.repository }}
      FETCH_DEPTH:   0
      TARGET_TRUNK:  ${{ inputs.trunk }}
      TARGET_STABLE: ${{ inputs.stable }}
      BUILD_USER:    ${{ github.actor }}
      BUILD_EMAIL:   ${{ github.actor }}@users.noreply.github.com
      BUILD_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Find customisation copy candidates"
        uses: octokit/graphql-action@v2.x
        id: find_customisations
        env:
          GITHUB_TOKEN: ${{ env.BUILD_TOKEN }}
        with:
          query: |
            query findCustomisations($searchexpr: String!) {
              search(query: $searchexpr, type: ISSUE, first: 100) {
                edges {
                  node {
                    ... on PullRequest {
                      state
                      number
                      title
                      baseRefName
                      headRefName
                      mergeable
                      isDraft
                      url
                    }
                  }
                }
              }
            }
          searchexpr: "type:pr state:open repo:${{ env.CUSTOM_REPO }} base:${{ env.TARGET_TRUNK }} label:custom label:approved"
          # searchexpr: "type:pr state:open repo:${{ env.CUSTOM_REPO }} base:${{ env.TARGET_TRUNK }} base:${{ env.TARGET_STABLE }} label:custom label:build-ready"
          # note that the search has OR semantice for `base:`, but AND semantics for `label:` !
          # see: https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-label      

      - name: Checkout build repo
        id: checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ env.CUSTOM_REPO }}
          ref: ${{ env.TARGET_STABLE }}
          fetch-depth: ${{ env.FETCH_DEPTH }}
          token: ${{ env.BUILD_TOKEN }}
      
      - name: Prepare repo for modifications
        id: prepare_repo
        run: |
          # some settings are mandatory for commits
          git config user.name $BUILD_USER
          git config user.email $BUILD_EMAIL
        
          #avoid some spoiling warnings
          git config merge.verbosity 1
          git config advice.skippedCherryPicks false          


      - name: Create missing stables
        id: copy_branches
        run: |
            # branch copies
            set +e  
            failed=0
            pulls=$(echo '${{ steps.find_customisations.outputs.data }}' | jq -s '.[].search.edges | map(.node)')
            stablebranch="${{ env.TARGET_STABLE }}"
            while IFS= read -r pr; do
                prnr=$(echo $pr | jq -r '.number')
                prbranch=$(echo $pr | jq -r '.headRefName')
                trunkbranch=$(echo $pr | jq -r '.baseRefName')                
                copybranch="backport/nmc/${prnr}/${stablebranch}"
                
                # Check if the new branch already exists
                if git ls-remote --heads origin ${copybranch} | grep -q ${copybranch}; then
                  echo "::info:: Keep existing ${copybranch} untouched"
                  continue
                fi

                # copy and rebase
                git checkout $prbranch
                git branch --copy $prbranch $copybranch

                git checkout $stablebranch
                git checkout $trunkbranch
                git rebase --merge --onto $stablebranch --fork-point $trunkbranch $copybranch
                result=$?
                if [ $result = 0 ]; then
                    git push origin $copybranch
                    echo ":white_check_mark: ${branch} -> ${copybranch} created!" >> $GITHUB_STEP_SUMMARY
                else
                    echo ::error::"REBASE conflicts: ${copybranch} from ${prbranch}!"
                    git diff --diff-filter=U
                    echo ":no_entry_sign: ${copybranch} from ${prbranch} does not merge (skipped)!" >> $GITHUB_STEP_SUMMARY
                    ((failed++))
                    git rebase --abort
                    git checkout $stablebranch
                    git branch -D $copybranch
                fi
            done < <(echo ${pulls} | jq -c -r '.[] | @json')
            set -e
            if ((failed>0)); then
                exit 1  
            fi
    
        ###
        # after copying the branches to stable, create PRs for the successful ones 
      - name: "Find existing stable PR"
        uses: octokit/graphql-action@v2.x
        if: ${{ success() || failure() }}
        id: find_backport_pr
        env:
          GITHUB_TOKEN: ${{ env.BUILD_TOKEN }}
        with:
          query: |
              query findStables($searchexpr: String!) {
                search(query: $searchexpr, type: ISSUE, first: 100) {
                  edges {
                    node {
                      ... on PullRequest {
                        baseRefName
                        headRefName
                      }
                    }
                  }
                }
              }
          searchexpr: "type:pr state:open repo:${{ env.CUSTOM_REPO }} base:${{ env.TARGET_STABLE }} label:test label:custom label:approved"    
          # searchexpr: "type:pr state:open repo:${{ env.CUSTOM_REPO }} base:${{ env.TARGET_STABLE }} label:test label:custom label:approved"    

      - name: Create missing stable/backport PRs
        id: stable_prs
        if: ${{ success() || failure() && steps.find_backport_pr.outcome == 'success' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            # stable backport PR creation
            set +e  
            failed=0
            pulls=$(echo '${{ steps.find_customisations.outputs.data }}' | jq -s '.[].search.edges | map(.node)')
            stablepulls=$(echo '${{ steps.find_backport_pr.outputs.data }}' | jq -s '.[].search.edges | map(.node)')
            while IFS= read -r pr; do
                title=$(echo $pr | jq -r '.title')
                prnr=$(echo $pr | jq -r '.number')
                body=$(echo $pr | jq -r '.body')
                url=$(echo $pr | jq -r '.url')
                prbranch=$(echo $pr | jq -r '.headRefName')
                stablebranch="${{ env.TARGET_STABLE }}"
                copybranch="backport/nmc/${prnr}/${stablebranch}"
                
                # skip if PR already exists
                if [[ "$(echo ${stablepulls}  | jq --arg st "${stablebranch}" --arg bp "${copybranch}" '.[] | select(.baseRefName == $st and .headRefName == $bp)')" ]]; then
                    echo "::info:: Existing PR for ${copybranch}, skip PR creation"
                    continue
                fi                  

                # skip if no backport branch is available
                if ! git ls-remote --heads origin ${copybranch} | grep -q ${copybranch}; then
                    echo "::info:: No ${copybranch}, skip PR creation"
                    ((failed++))
                    continue
                fi                  

                stableprtitle="[${stablebranch}] ${title}"
                stableprdescription="
            __${stablebranch} baseline for__
            __[#${prnr} ${stableprtitle}](${url})__
            "
                gh pr create --title "${stableprtitle}" --body "${stableprdescription}" \
                    --base "${stablebranch}" --head "${copybranch}" --label custom 
                echo ":white_check_mark: New PR #{prnr} ${stableprtitle} (not labelled for build, please check)"
            done < <(echo ${pulls} | jq -c -r '.[] | @json')
            set -e
            if ((failed>0)); then
                exit 1  
            fi

  